import type { Metadata } from "next";
import localFont from "next/font/local";
import "../../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <div className="flex flex-col px-5 lg:px-0 justify-around w-full z-10 m-auto max-w-[1500px]">
            {children}
        </div>
  );
}
